<a href="https://colab.research.google.com/github/joshi-nitant/083_Nitant_Joshi/blob/master/Lab5/083_2_linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [6]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [7]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [8]:

# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 69.,  96.,  70.],
         [102.,  43.,  37.],
         [ 91.,  88.,  64.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.]]), tensor([[103., 119.],
         [ 22.,  37.],
         [ 81., 101.],
         [103., 119.],
         [ 56.,  70.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [9]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[0.0748, 0.0456, 0.1499],
        [0.0955, 0.3244, 0.3621]], requires_grad=True)
---------
Parameter containing:
tensor([-0.4183,  0.5695], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [10]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [11]:
# Import nn.functional
import torch.nn.functional as F

In [13]:
# Define loss function
loss_fn = F.mse_loss

In [14]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(3092.8308, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [15]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))


In [16]:

# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(16.1018, grad_fn=<MseLossBackward>)


In [17]:

# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 58.3027,  71.3401],
        [ 81.4444,  98.9748],
        [118.3745, 134.7551],
        [ 28.1233,  42.5342],
        [ 96.4180, 113.1091],
        [ 58.3027,  71.3401],
        [ 81.4444,  98.9748],
        [118.3745, 134.7551],
        [ 28.1233,  42.5342],
        [ 96.4180, 113.1091],
        [ 58.3027,  71.3401],
        [ 81.4444,  98.9748],
        [118.3745, 134.7551],
        [ 28.1233,  42.5342],
        [ 96.4180, 113.1091]], grad_fn=<AddmmBackward>)

In [18]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [19]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(4.6856, grad_fn=<MseLossBackward>)


## Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
 
 
## Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [20]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [21]:

# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.60591828 0.00854811 0.43183106]
 [0.45222619 0.57146846 0.68340591]]
Biases:
[[0.62451996 0.17250447]
 [0.34991926 0.5053128 ]
 [0.14439686 0.41991325]
 [0.79733736 0.9854972 ]
 [0.23851905 0.28481634]
 [0.8562788  0.10744575]
 [0.83046329 0.78215157]
 [0.28206245 0.59198783]
 [0.56375855 0.75297125]
 [0.57190776 0.90461196]
 [0.16512141 0.09427178]
 [0.27369316 0.61440096]
 [0.49854645 0.65424621]
 [0.4590481  0.10978696]
 [0.41957612 0.12718487]]


In [22]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [23]:

# Generate predictions
preds = model(inputs)

In [24]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[ 63.99801345 100.85985726]
 [ 83.87790442 135.68509882]
 [ 79.05093547 155.97790819]
 [ 78.94632001  96.97173088]
 [ 73.09567329 134.18780941]
 [ 64.22977228 100.79479854]
 [ 84.35844845 135.96193759]
 [ 79.18860106 156.14998277]
 [ 78.7127412   96.73920494]
 [ 73.42906199 134.80760503]
 [ 63.53861489 100.78162457]
 [ 83.80167832 135.79418697]
 [ 79.40508506 156.21224115]
 [ 78.60803075  96.09602064]
 [ 73.27673036 134.03017794]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [25]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [26]:
# Compute loss
loss = mse(preds, targets)
print(loss)

2448.7679612824145


In [27]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[  451.47128948 -1979.66659534  -702.16503033]
 [ 5826.48889621  4904.37228553  3269.11664937]]
biases_grad:
[[ 1.06640179  4.11464763]
 [ 0.38372059  4.62467984]
 [-5.32654194  3.06372109]
 [ 7.59284267  7.99623078]
 [-3.98724356  2.02504125]
 [ 1.09730297  4.10597314]
 [ 0.44779313  4.66159168]
 [-5.30818653  3.08666437]
 [ 7.56169883  7.96522733]
 [-3.94279173  2.10768067]
 [ 1.00514865  4.10421661]
 [ 0.37355711  4.63922493]
 [-5.27932199  3.09496549]
 [ 7.54773743  7.87946942]
 [-3.96310262  2.00402373]]


Adjust weights

In [28]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [29]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.60140357 0.02834477 0.43885272]
 [0.3939613  0.52242474 0.65071475]]
Biases:
[[0.6245093  0.17246332]
 [0.34991543 0.50526655]
 [0.14445012 0.41988261]
 [0.79726144 0.98541724]
 [0.23855893 0.28479609]
 [0.85626782 0.10740469]
 [0.83045881 0.78210496]
 [0.28211553 0.59195697]
 [0.56368293 0.7528916 ]
 [0.57194718 0.90459088]
 [0.16511135 0.09423074]
 [0.27368942 0.61435456]
 [0.49859924 0.65421526]
 [0.45897262 0.10970816]
 [0.41961575 0.12716483]]


In [30]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

1840.5754633408726


In [31]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [32]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

14.5240597549105


In [33]:
# Print predictions
print(preds)

[[ 58.27206845  70.67497577]
 [ 81.95471285  99.62830512]
 [117.2110338  134.20654388]
 [ 26.35345781  40.84517855]
 [ 98.66178094 115.24324476]
 [ 58.50376518  70.60993449]
 [ 82.43512811  99.90506972]
 [117.3486625  134.37857236]
 [ 26.11994158  40.61271491]
 [ 98.99508031 115.86287429]
 [ 57.81279299  70.59676405]
 [ 81.87850717  99.73736405]
 [117.56508849 134.44081406]
 [ 26.01525919  39.96970297]
 [ 98.84278949 115.08565553]]


In [34]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
